### ISSUE TITLE
evaluate chat clients (matrix, slack, discord)

### ISSUE THREAD

**Issue by larnsce** [openwashdata/book#1]

**Comment by larnsce** [comment]
Hih @mbannert. Whichever alternative turns out to be the most suitable, I also want to use it for our group in general. There should channels for:

- each class that we teach (which is closed after the class is done)
- an alumni channel for all students that participated in our classes
- an internal channel for our team
- a channel that would allow us to invite people external to our organisation (like Slack Connect)

Please add these considerations when you evaluate the clients.

**Comment by larnsce** [comment]
Next steps:

- evaluate how matrix works exactly and if it's worth to implement it (timeframe 4 weeks from now)
- assess the user perspective and exact needs

**Comment by mbannert** [comment]
Here is a bit of a summary of Matrix works: 

- matrix calls itself a *decentralized conversation store* rather than a chat protocol. (conceptually similar to git) 
- clients, i.e., local chat or VoIP clients have *homeservers*. they use the client-server-api to send messages to these homeservers. 
- homeservers use a server-server API to communicate with each other. [synapse](https://github.com/matrix-org/synapse/) is the most popular matrix homeserver. They got a nice ansible playbook to bootstrap things https://matrix.org/docs/guides/installing-synapse

**Comment by mbannert** [comment]
The key question is: If we were to put emphasis on self-hosting a chat, how is it operated in the long run? The server has to run somewhere. On the other hand it would be a contribution to the WASH community to have such a server.

**Comment by mbannert** [comment]
@larnsce , can you do the following: 

- download element desktop client
- read this: https://ethz.ch/staffnet/en/it-services/catalogue/communication/chat.html (the customer groups part is relevant) 
- use staffnet to login into ETH Matrix server

This enables you to create new rooms, including entirely public ones. Maybe this is already sufficient.

**Comment by larnsce** [comment]
Done. I have the https://chat.ethz.ch/staffchat/ open in my browser, though, and not in the element desktop client.

**Comment by larnsce** [comment]
Okay, now I have figured out how to connect to the ETHZ server using the element client.

This is great! 

What I am still confused about is that this is supposed to be only useable for staff at ETH. How would someone else log into the staffchat.ethz.ch server?

**Comment by mbannert** [comment]
I did more research on external guests and it looks like this is not possible with the ETH service. Yet, there are options. 
I found out an old connection within ETH is responsible for hosting and reached out to him so we know for sure. 
I pretty sure the question is not unprecedented if this limitation really exists and he will be at least able to tell us what others did. 

I am still in idealistic mode here wanting to hold on to matrix because

- the approach fits the spirit of our project
- we can switch to Slack et al. at any given time. 

but most importantly we can have multiple matrix homeservers and could use matrix.org itself for stuff that involves people outside ETH.

**Comment by mbannert** [comment]
Ok, another update: 

There are so called *spaces* that can contain multiple rooms on the same homeserver. It looks like ETH allows for rooms that are entirely public, but not sharing private rooms with people on other homeservers.  Even if this is confirmed, we can still choose matrix but just use matrix.org as a homeserver instead of ETH. 

Long story short: I'd give matrix a shot.

**Comment by larnsce** [comment]
Great, thanks for the update. I am happy if you go ahead, set it up, and write some brief guidelines for our website, so that we can share it with the community. Also as part of the first newsletter issue.
