### ISSUE TITLE
Draft VMOST strategy as a 1-pager (A4 printed with back and front)

### ISSUE THREAD

**Issue by larnsce** [openwashdata/book#18]

**Comment by larnsce** [comment]
@mbannert

**Comment by mbannert** [comment]
In general, I like it a lot. I wonder if we could use vision and mission on our website rather front and center, maybe with carousel-like stock or AI image on a cover page. 

Also the finer grained action items are great. 👏 

The only thing that I miss a bit is the direct link to tne newsletter. What the document does for the newsletter, is set a certain quality standard. Yet it lacks a campaign type of thinking. So how about: 

- `hello world` campaign
-  `events` campaign
-  `submission` campaign

What frequency are we looking at? Given that there is blog post, we could go for: monthly or quarterly newsletters. The latter would also align well with our 30-60-90 evaluation periods and it become a 'tradition' to write a more comprehensive newsletter for our audience about the progress. 

What do you think ?

**Comment by larnsce** [comment]
Thank you for the great feedback.

I agree with you, the newsletter strategy needs to be developed further. I like the campaign type thinking, but also see the newsletter as a regular update to the community on progress. 

We could do irregular campaigns, and then a monthly newsletter. I initially thought of a bi-weekly newsletter, but that's probably unrealistic, both in terms of workload, but also content.

I am going to work on the newsletter strategy until our next sprint meeting.

#19

**Comment by mbannert** [comment]
Maybe it's just me but I could not think of anything I'd want a weekly or bi-weekly newsletter for. To me,  monthly should be the highest frequency we consider, if not quarterly or something in between. I guess I good digest and well edit newsletter is worth more. 

If the purpose was to nudge people more, I'd rather go for Slack communities and social media, because: 

- easier to produce content, less substantial content needed 
- higher frequency more common

**Comment by larnsce** [comment]
Closing tissue. Follow up issue is here: #19
